### PR TITLE
added my protfolio and name in README.md and updated users.json

### PR DESCRIPTION
**Pull request by someshium**

### CODE REVIEW

**Review by BRO3886 — CHANGES_REQUESTED** [review]
Please correct the image url in `users.json`

The url should be like this: https://i.ibb.co/RTh56dk/tanut.png

**Comment by someshium** [comment]
i have modified the link as you told. thanks.

**Review by BRO3886 — CHANGES_REQUESTED** [review]
Can you fix the merge conflicts first?

Get up-to-date with master and add in your details

**Comment by someshium** [comment]
hey, i just merged the conflict. thanks for pointing out.

**Review by akshatvg — APPROVED** [review]

**Pull request merged**
