### PR TITLE
Added Link of the Portfolio & updated Users.json

### PR DESCRIPTION
**Pull request by Neon-K9**

### CODE REVIEW

**Comment by Neon-K9** [comment]
@ATechnoHazard @akshatvg @Geek-ubaid @L04DB4L4NC3R @tanut2539 
Hey guys,
I believe the Commits that I want merge are sufficient,
if not, Let me know the changes i should make!

**Comment by akshatvg** [comment]
@Neon-K9 I had to change the users.json file to optimise the website and hence there are conflicts.

Please make the required changes.

**Comment by Neon-K9** [comment]
Hey @akshatvg ,
Thank you for Pointing out that Conflict,
I've made those Changes,
Check them out and let me know 
(^_^)

**Comment by Neon-K9** [comment]
@ATechnoHazard @akshatvg @Geek-ubaid @L04DB4L4NC3R @tanut2539
Hey guys,
Just resolved the Conflicting users.json file
Hoping this contributes to the Project

**Comment by Neon-K9** [comment]
Hey @akshatvg ,

Sorry to interrupt,
But I had a slightest request,
If you could Label this PR as 'hactoberfest-accepted'
It would be a great help to Complete my 4PRs for Hactoberfest
Thank you 😊

**Comment by akshatvg** [comment]
Hey @Neon-K9 !

We have added the `hacktoberfest` topic to the repo and since your PR has been merged, it'll be considered for hacktoberfest. Don't worry.

**Pull request merged**
