### PR TITLE
Added my credentials

### PR DESCRIPTION
**Pull request by Gauravsaha-97**

### CODE REVIEW

**Review by BRO3886 — APPROVED** [review]

**Review by BRO3886 — CHANGES_REQUESTED** [review]
Please correct your image url in `users.json`

This link does not yield the correct image
[https://i.ibb.co/yXDdrbF/IMG-5itfo3.jpg](https://i.ibb.co/yXDdrbF/IMG-5itfo3.jpg)

**Comment by Gauravsaha-97** [comment]
@BRO3886 Corrected it!!

**Comment by BRO3886** [comment]
[This](https://i.ibb.co/gJRHnMk/IMG-5itfo3.jpg) is not the correct image

We need a site preview like this:
image

**Comment by L04DB4L4NC3R** [comment]
@BRO3886 can you make a change in the readme instructions to make it more apparent, or maybe use a workflow which can automatically take a screenshot of a user's website?

**Comment by BRO3886** [comment]
Already did, made a PR @L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
Merged it #19

**Review by BRO3886 — APPROVED** [review]

**Comment by L04DB4L4NC3R** [comment]
@BRO3886 @Gauravsaha-97 fix the merge conflict

**Review by BRO3886 — CHANGES_REQUESTED** [review]
@Gauravsaha-97 can you please fix the conflicting files?

**Comment by Gauravsaha-97** [comment]
@BRO3886 sorry for the late response. I have resolved all the conflicts.

**Review by BRO3886 — APPROVED** [review]

**Pull request merged**
