### PR TITLE
Added my portfolio website

### PR DESCRIPTION
**Pull request by Alleny244**

### CODE REVIEW

**Comment by akshatvg** [comment]
@Alleny244 I had to change the users.json file to optimise the website.

Please make the required changes.

**Comment by Alleny244** [comment]
> @Alleny244 I had to change the users.json file to optimise the website.
> 
> Please make the required changes.

Yes I have made the required changes

**Comment by akshatvg** [comment]
@Alleny244 there's still a merge conflict. Please fix that.

**Comment by L04DB4L4NC3R** [comment]
@Alleny244 I have resolved your conflict. Just add your portfolio image raw url in `users.json` and you will be good to go.

**Comment by Geek-ubaid** [comment]
@Alleny244 do the changes requested, PR getting stale.

**Comment by Alleny244** [comment]
> @Alleny244 do the changes requested, PR getting stale.

Yes I Have updated the image url

**Comment by Alleny244** [comment]
> @Alleny244 I have resolved your conflict. Just add your portfolio image raw url in `users.json` and you will be good to go.

Yeah I have added it

**Comment by Alleny244** [comment]
> @Alleny244 do the changes requested, PR getting stale.

is it okay now?

**Comment by Geek-ubaid** [comment]
> > @Alleny244 do the changes requested, PR getting stale.
> 
> is it okay now?

Yes it's fine.

**Comment by Geek-ubaid** [comment]
All changes added merging it.

**Pull request merged**
